- name: ExportVM
  hosts: localhost
  tasks:
    - name: info
      debug:
        msg: "IP: {{fusionComputeIP}} >>>> VM a exportar: {{vmName2Export}}"
        
    - name: login
      uri: 
       url: "https://{{fusionComputeIP}}:7443/service/session"
       validate_certs: no
       return_content: yes
       body_format: json
       method: POST
       headers: "{{headersLogin}}" 
      register: login
        
    - name: Print token
      debug:
        var: login.x_auth_token
      
    
    - name: get siteID
      uri: 
       url: "https://{{fusionComputeIP}}:7443/service/sites" #siteUri: /service/sites/
       validate_certs: no
       return_content: yes
       body_format: json
       method: GET
       headers: "{{headersGET}}"         
      register: sites
      
    - name: Print sites 
      debug:
        var: sites.json
      
    - name: get sites uri #siteUri: /service/sites/site_id/
      debug: 
        msg="{{ sites.json | json_query("sites[*].uri") }}"
      register: site_uri    
        
    - name: Print sitwUri site0
      debug:
        var: site_uri.msg[0]    
        
    - name: get VMs 
      uri: #<site_uri>/<site_id>/vms
       url: "https://{{fusionComputeIP}}:7443/{{site_uri.msg[0]}}/vms" 
       validate_certs: no
       return_content: yes
       body_format: json
       method: GET
       headers: "{{headersGET}}"
      register: vms 
      
    - name: Print vms 
      debug:
        var: vms.json
   
    - name: Print only VMnames 
      debug: 
        msg="{{ vms.json | json_query("vms[*].name") }}"
   
    - name: Print all VMnames and Uri
      debug: msg="{{ vms.json | json_query(nameanduri) }}"
      vars:
        nameanduri: "vms[*].{name:name,uri:uri}"
       
    - name: getUri for VM to export
      debug: msg="{{ vms.json | json_query(nameanduri) }}"
      vars:
        nameanduri: "vms[? name=='{{vmName2Export}}'].uri"
      register: vm_uri
      
    - name: Print vm uri ti export
      debug:
        var: vm_uri.msg[0]
    
    - name: exportVM 
      uri: #<vm_uri>/<id>/action/export HTTP/1.1 
       url: "https://{{fusionComputeIP}}:7443/{{vm_uri.msg[0]}}/action/export" 
       validate_certs: no
       return_content: yes
       body_format: json
       method: POST
       headers: "{{headersGET}}"
       body: 
         'name': "test"
         'url': "//10.50.5.238/e"
         #'protocol': "nfs" by dfault cifs
         'username': "NULL"
         'password': "NULL"
         
      register: exportVM
      
      
      
        
