- name: login
  hosts: localhost
  tasks:
    - name: login
      uri: 
       url: "https://10.50.25.151:7443/service/session"
       validate_certs: no
       return_content: yes
       body_format: json
       method: POST
       headers: 
         Content-Type: 'application/json; charset=UTF-8'
         Accept: 'application/json;version=3;charset=UTF-8'
         Accept-Language: 'en_US'
         X-Auth-User: 'api'
         X-Auth-Key: 'Huawei12#$'
         X-Auth-UserType: '2'
         X-ENCRIPT-ALGORITHM: '1'
      register: login
        
    - name: Print token
      debug:
        var: login.x_auth_token
      
    
    - name: get siteID
      uri: 
       url: "https://10.50.25.151:7443/service/sites"
       validate_certs: no
       return_content: yes
       body_format: json
       method: GET
       headers: 
         Content-Type: 'application/json; charset=UTF-8'
         Accept: 'application/json;version=3;charset=UTF-8'
         X-Auth-Token: '{{login.x_auth_token}}'
      register: sites
      
    - name: Print sites 
      debug:
        var: sites.json
      
    - name: get sites uri
      debug: msg="{{ sites.json | json_query(jmesquery) }}"
      vars:
        jmesquery: "[*].uri"
        
    - name: Display all cluster names
      ansible.builtin.debug:
        var: item
      loop: "{{ sites.json | community.general.json_query('sites.json[*].uri') }}"    
      
         
    
