- name: test connection
  hosts: localhost
  tasks:
     - name: Leaving a mark
       uri: 
        url: "https://10.50.25.151:7443/service/versions"
        follow_redirects: none
        content: {"verify": false}
        method: get
        return_content: yes
