---
- name: makesure bigip is online
  hosts: 10.50.25.151
  connection: local
  gather_facts: false
  
   tasks:
    - name: check bigip to make sure it is online
      uri:
        url: "https://10.50.25.151:7443/service/versions"
        method: GET
